apiVersion: v1
kind: Service
metadata:
    name: ping-pong-srvc
spec:
    type: ClusterIP
    selector:
        app: ping-pong
    ports:
        - port: 4321
          protocol: TCP
          targetPort: 6543
