apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: log-ping-ingress
spec:
    rules:
        - http:
              paths:
                  - path: /pingpong
                    pathType: Prefix
                    backend:
                        service:
                            name: ping-pong-srvc
                            port:
                                number: 4321
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: log-output-srvc
                            port:
                                number: 8765
