apiVersion: v1
kind: Service
metadata:
    name: log-output-srvc
spec:
    type: ClusterIP
    selector:
        app: log-output
    ports:
        - port: 8765
          protocol: TCP
          targetPort: 9876